version: '3'

services:
  nextjs:
    container_name: nextjsportfolio
    build:
      context: ./
    image: nextjsportfolio
    ports:
      - '3001:3001'
    restart: unless-stopped
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge